global using Ecommerce.Server;
global using Ecommerce.Server.Data;
global using Ecommerce.Server.Services.AuthService;
global using Ecommerce.Server.Services.CartService;
global using Ecommerce.Server.Services.CategoryService;
global using Ecommerce.Server.Services.OrderService;
global using Ecommerce.Server.Services.ProductService;
global using Ecommerce.Shared;
global using Microsoft.EntityFrameworkCore;
